import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import ts from 'typescript'
import { afterEach, describe, expect, it } from 'vitest'

import { DEFAULT_TYPES_FILENAME, generateTypeDeclarations, writeTypesWorkspace } from '../../../src/lib/app/types.js'
import { JSON_SCHEMA_NAMES, JSON_SCHEMA_RELATIVE_PATHS } from '../../../src/lib/app/json-schema.js'

const directories: string[] = []
const GENERATED_AT = new Date('2026-09-08T21:54:32.000Z')

function compileDiagnostics(fileName: string, contents: string): readonly ts.Diagnostic[] {
  const compilerOptions: ts.CompilerOptions = {
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    types: []
  }
  const source = ts.createSourceFile(fileName, contents, ts.ScriptTarget.Latest, true)
  const host = ts.createCompilerHost(compilerOptions)
  const readSourceFile = host.getSourceFile.bind(host)
  const fileExists = host.fileExists.bind(host)
  const readFile = host.readFile.bind(host)
  host.getSourceFile = (requestedFile, ...args) =>
    requestedFile === fileName ? source : readSourceFile(requestedFile, ...args)
  host.fileExists = requestedFile => requestedFile === fileName || fileExists(requestedFile)
  host.readFile = requestedFile => (requestedFile === fileName ? contents : readFile(requestedFile))
  return ts.getPreEmitDiagnostics(ts.createProgram([fileName], compilerOptions, host))
}

async function workspace(): Promise<string> {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'ghl-types-'))
  directories.push(directory)
  return directory
}

afterEach(async () => {
  await Promise.all(directories.splice(0).map(directory => fs.rm(directory, { recursive: true, force: true })))
})

describe('generateTypeDeclarations', () => {
  it('emits valid readonly declarations for every editable configuration surface', () => {
    const declarations = generateTypeDeclarations(GENERATED_AT)
    const fileName = path.resolve('/virtual', DEFAULT_TYPES_FILENAME)

    expect(compileDiagnostics(fileName, declarations)).toEqual([])
    expect(declarations).toMatch(
      /Generated by @gohighlevel\/marketplace-cli on 2026-09-08T21:54:32\.000Z[\s\S]*Do not edit manually/
    )
    expect(declarations).toContain('export interface GhlAppManifest')
    expect(declarations).toContain('readonly basicInfo: GhlBasicInfo;')
    expect(declarations).toContain("readonly billingType: 'free' | 'freemium' | 'paid';")
    expect(declarations).toContain('export interface GhlWebhookManifest')
    expect(declarations).toContain('export interface GhlWorkflowActionManifest')
    expect(declarations).toContain('export interface GhlWorkflowTriggerManifest')
    expect(declarations).toContain('export interface GhlSubscriptionManifest')
    expect(declarations).toContain('export interface GhlUsageBasedManifest')
    expect(declarations).not.toMatch(/^\/\//mu)
  })
})

describe('writeTypesWorkspace', () => {
  it('writes declarations and every JSON Schema to an existing workspace', async () => {
    const directory = await workspace()
    const result = await writeTypesWorkspace(directory, { generatedAt: GENERATED_AT })

    expect(result.declarationFile).toBe(path.join(directory, DEFAULT_TYPES_FILENAME))
    await expect(fs.readFile(result.declarationFile, 'utf8')).resolves.toBe(generateTypeDeclarations(GENERATED_AT))
    expect(result.schemaFiles).toEqual(
      JSON_SCHEMA_NAMES.map(name => path.join(directory, JSON_SCHEMA_RELATIVE_PATHS[name]))
    )
    await expect(fs.stat(result.vscodeSettingsFile)).resolves.toBeDefined()
  })

  it('supports a nested custom .d.ts path and rejects paths outside the workspace', async () => {
    const directory = await workspace()
    const result = await writeTypesWorkspace(directory, {
      generatedAt: GENERATED_AT,
      output: 'generated/ghl-types.d.ts'
    })

    expect(result.declarationFile).toBe(path.join(directory, 'generated', 'ghl-types.d.ts'))
    await expect(writeTypesWorkspace(directory, { output: '../outside.d.ts' })).rejects.toThrow(/inside.*workspace/i)
    await expect(writeTypesWorkspace(directory, { output: 'generated/types.ts' })).rejects.toThrow(/\.d\.ts/i)
  })

  it('rejects a symbolic-link output without changing its target', async () => {
    const directory = await workspace()
    const targetDirectory = await workspace()
    const target = path.join(targetDirectory, 'target.d.ts')
    const output = path.join(directory, DEFAULT_TYPES_FILENAME)
    await fs.writeFile(target, 'user content')
    await fs.symlink(target, output)

    await expect(writeTypesWorkspace(directory)).rejects.toThrow(/symbolic link/i)
    await expect(fs.readFile(target, 'utf8')).resolves.toBe('user content')
  })
})
