import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import ts from 'typescript'
import { afterEach, describe, expect, it } from 'vitest'

import { DEFAULT_TYPES_FILENAME, generateTypeDeclarations, writeTypesWorkspace } from '../../../src/lib/app/types.js'
import { JSON_SCHEMA_NAMES, JSON_SCHEMA_RELATIVE_PATHS } from '../../../src/lib/app/json-schema.js'
import type { WorkflowActionsManifest } from '../../../src/lib/workflows/actions/manifest.js'
import { writeWorkflowActionsWorkspace } from '../../../src/lib/workflows/actions/workspace.js'

const directories: string[] = []
const GENERATED_HEADER = [
  '/*',
  ' * Auto generated by @gohighlevel/marketplace-cli',
  ' * Run `ghl app types` to regenerate. Do not edit manually.',
  ' */'
].join('\n')

function compileDiagnostics(fileName: string, contents: string): readonly ts.Diagnostic[] {
  const compilerOptions: ts.CompilerOptions = {
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    types: []
  }
  const source = ts.createSourceFile(fileName, contents, ts.ScriptTarget.Latest, true)
  const host = ts.createCompilerHost(compilerOptions)
  const readSourceFile = host.getSourceFile.bind(host)
  const fileExists = host.fileExists.bind(host)
  const readFile = host.readFile.bind(host)
  host.getSourceFile = (requestedFile, ...args) =>
    requestedFile === fileName ? source : readSourceFile(requestedFile, ...args)
  host.fileExists = requestedFile => requestedFile === fileName || fileExists(requestedFile)
  host.readFile = requestedFile => (requestedFile === fileName ? contents : readFile(requestedFile))
  return ts.getPreEmitDiagnostics(ts.createProgram([fileName], compilerOptions, host))
}

async function workspace(): Promise<string> {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'ghl-types-'))
  directories.push(directory)
  return directory
}

async function readTypeScriptConfig(file: string): Promise<Record<string, unknown>> {
  const parsed = ts.parseConfigFileTextToJson(file, await fs.readFile(file, 'utf8'))
  if (parsed.error) throw new Error(ts.flattenDiagnosticMessageText(parsed.error.messageText, '\n'))
  return parsed.config as Record<string, unknown>
}

afterEach(async () => {
  await Promise.all(directories.splice(0).map(directory => fs.rm(directory, { recursive: true, force: true })))
})

describe('generateTypeDeclarations', () => {
  it('emits valid readonly declarations for every editable configuration surface', () => {
    const declarations = generateTypeDeclarations()
    const fileName = path.resolve('/virtual', DEFAULT_TYPES_FILENAME)

    expect(compileDiagnostics(fileName, declarations)).toEqual([])
    expect(declarations.startsWith(GENERATED_HEADER)).toBe(true)
    expect(declarations).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
    expect(declarations).toContain('export interface GhlAppManifest')
    expect(declarations).toContain('readonly basicInfo: GhlBasicInfo;')
    expect(declarations).toContain("readonly billingType: 'free' | 'freemium' | 'paid';")
    expect(declarations).toContain('export interface GhlWebhookManifest')
    expect(declarations).toContain('export interface GhlWorkflowActionManifest')
    expect(declarations).toContain('export interface GhlWorkflowTriggerManifest')
    expect(declarations).toContain('export interface GhlSubscriptionManifest')
    expect(declarations).toContain('export interface GhlUsageBasedManifest')
    expect(declarations).not.toMatch(/^\/\//mu)
  })
})

describe('writeTypesWorkspace', () => {
  it('writes declarations and every JSON Schema to an existing workspace', async () => {
    const directory = await workspace()
    const result = await writeTypesWorkspace(directory)

    expect(result.declarationFile).toBe(path.join(directory, DEFAULT_TYPES_FILENAME))
    expect(result.typescriptConfig).toEqual({
      file: path.join(directory, 'tsconfig.json'),
      status: 'created'
    })
    await expect(fs.readFile(result.declarationFile, 'utf8')).resolves.toBe(generateTypeDeclarations())
    await expect(fs.readFile(result.typescriptConfig.file, 'utf8')).resolves.toBe(
      `${GENERATED_HEADER}\n${JSON.stringify({ include: [DEFAULT_TYPES_FILENAME, 'src/**/*'] }, null, 2)}\n`
    )
    expect(result.schemaFiles).toEqual(
      JSON_SCHEMA_NAMES.map(name => path.join(directory, JSON_SCHEMA_RELATIVE_PATHS[name]))
    )
    await expect(fs.stat(result.vscodeSettingsFile)).resolves.toBeDefined()
  })

  it('supports a nested custom .d.ts path and rejects paths outside the workspace', async () => {
    const directory = await workspace()
    const result = await writeTypesWorkspace(directory, { output: 'generated/ghl-types.d.ts' })

    expect(result.declarationFile).toBe(path.join(directory, 'generated', 'ghl-types.d.ts'))
    await expect(fs.readFile(result.typescriptConfig.file, 'utf8')).resolves.toContain('generated/ghl-types.d.ts')
    await expect(writeTypesWorkspace(directory, { output: '../outside.d.ts' })).rejects.toThrow(/inside.*workspace/i)
    await expect(writeTypesWorkspace(directory, { output: 'generated/types.ts' })).rejects.toThrow(/\.d\.ts/i)
  })

  it('creates a TypeScript project that can import the generated declarations', async () => {
    const directory = await workspace()
    const sourceDirectory = path.join(directory, 'src')
    await fs.mkdir(sourceDirectory)
    await fs.writeFile(
      path.join(sourceDirectory, 'manifest.ts'),
      "import type { GhlAppManifest } from '../ghl-app.js'\nexport type AppManifest = GhlAppManifest\n"
    )
    await writeTypesWorkspace(directory)

    const parsed = ts.getParsedCommandLineOfConfigFile(
      path.join(directory, 'tsconfig.json'),
      {},
      {
        ...ts.sys,
        onUnRecoverableConfigFileDiagnostic: () => undefined
      }
    )
    expect(parsed).toBeDefined()
    expect(parsed?.fileNames).toEqual(
      expect.arrayContaining([path.join(directory, DEFAULT_TYPES_FILENAME), path.join(sourceDirectory, 'manifest.ts')])
    )
    expect(ts.getPreEmitDiagnostics(ts.createProgram(parsed?.fileNames ?? [], parsed?.options ?? {}))).toEqual([])
  })

  it('keeps the isolated workflow-action project out of the root TypeScript project', async () => {
    const directory = await workspace()
    await fs.writeFile(
      path.join(directory, 'ghl-app.json'),
      JSON.stringify({ schemaVersion: 1, appId: 'app-1', versionId: 'version-1' })
    )
    const manifest: WorkflowActionsManifest = {
      schemaVersion: 1,
      appId: 'app-1',
      actions: [
        {
          key: 'typed_action',
          versions: [{ version: '1.0', status: 'draft', info: { name: 'Typed action' } }]
        }
      ]
    }
    await writeWorkflowActionsWorkspace(directory, manifest, manifest)

    await writeTypesWorkspace(directory)

    const config = (await readTypeScriptConfig(path.join(directory, 'tsconfig.json'))) as { exclude: string[] }
    expect(config.exclude).toEqual(['src/modules/workflows/actions/code/**/*'])
  })

  it('migrates a broad root project once and preserves its existing exclusions', async () => {
    const directory = await workspace()
    await fs.writeFile(
      path.join(directory, 'ghl-app.json'),
      JSON.stringify({ schemaVersion: 1, appId: 'app-1', versionId: 'version-1' })
    )
    await fs.writeFile(
      path.join(directory, 'tsconfig.json'),
      `${JSON.stringify({ include: [DEFAULT_TYPES_FILENAME, 'src/**/*'], exclude: ['dist/**/*'] }, null, 2)}\n`
    )
    const manifest: WorkflowActionsManifest = {
      schemaVersion: 1,
      appId: 'app-1',
      actions: [
        {
          key: 'typed_action',
          versions: [{ version: '1.0', status: 'draft', info: { name: 'Typed action' } }]
        }
      ]
    }
    await writeWorkflowActionsWorkspace(directory, manifest, manifest)

    const first = await writeTypesWorkspace(directory)
    const second = await writeTypesWorkspace(directory)
    const configFile = path.join(directory, 'tsconfig.json')
    const config = (await readTypeScriptConfig(configFile)) as { exclude: string[] }
    const configContents = await fs.readFile(configFile, 'utf8')

    expect(first.typescriptConfig.status).toBe('updated')
    expect(second.typescriptConfig.status).toBe('unchanged')
    expect(config.exclude).toEqual(['dist/**/*', 'src/modules/workflows/actions/code/**/*'])
    expect(configContents.startsWith(GENERATED_HEADER)).toBe(true)
  })

  it('updates a commented tsconfig without losing developer settings and is idempotent', async () => {
    const directory = await workspace()
    const configFile = path.join(directory, 'tsconfig.json')
    await fs.writeFile(
      configFile,
      '{\n  /* Keep this project setting. */\n  "compilerOptions": { "strict": true },\n  "include": ["src/**/*"],\n}\n'
    )

    const first = await writeTypesWorkspace(directory)
    const firstContents = await fs.readFile(configFile, 'utf8')
    const second = await writeTypesWorkspace(directory)

    expect(first.typescriptConfig).toEqual({ file: configFile, status: 'updated' })
    expect(second.typescriptConfig).toEqual({ file: configFile, status: 'unchanged' })
    expect(await fs.readFile(configFile, 'utf8')).toBe(firstContents)
    expect(firstContents).toContain('/* Keep this project setting. */')
    expect(firstContents).toContain('"strict": true')
    expect(firstContents).toMatch(/"include":\s*\[\s*"src\/\*\*\/\*",\s*"ghl-app\.d\.ts"\s*]/)
  })

  it('preserves an existing config whose default source selection already includes declarations', async () => {
    const directory = await workspace()
    const configFile = path.join(directory, 'tsconfig.json')
    const contents = '{\n  "compilerOptions": { "strict": true } /* Keep compiler settings. */\n}\n'
    await fs.writeFile(configFile, contents)

    const result = await writeTypesWorkspace(directory)

    expect(result.typescriptConfig.status).toBe('unchanged')
    await expect(fs.readFile(configFile, 'utf8')).resolves.toBe(contents)
  })

  it('adds declarations to an explicit files list without changing its source selection', async () => {
    const directory = await workspace()
    const configFile = path.join(directory, 'tsconfig.json')
    await fs.writeFile(configFile, `${JSON.stringify({ files: ['src/index.ts'] }, null, 2)}\n`)

    const result = await writeTypesWorkspace(directory)
    const config = JSON.parse(await fs.readFile(configFile, 'utf8')) as { files: string[]; include?: string[] }

    expect(result.typescriptConfig.status).toBe('updated')
    expect(config.files).toEqual(['src/index.ts', DEFAULT_TYPES_FILENAME])
    expect(config.include).toBeUndefined()
  })

  it('updates an existing JavaScript project instead of creating a competing tsconfig', async () => {
    const directory = await workspace()
    const configFile = path.join(directory, 'jsconfig.json')
    await fs.writeFile(configFile, `${JSON.stringify({ include: ['src/**/*.js'] }, null, 2)}\n`)

    const result = await writeTypesWorkspace(directory)
    const config = JSON.parse(await fs.readFile(configFile, 'utf8')) as { include: string[] }

    expect(result.typescriptConfig).toEqual({ file: configFile, status: 'updated' })
    expect(config.include).toEqual(['src/**/*.js', DEFAULT_TYPES_FILENAME])
    await expect(fs.stat(path.join(directory, 'tsconfig.json'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('does not overwrite an invalid or linked TypeScript config', async () => {
    const directory = await workspace()
    const configFile = path.join(directory, 'tsconfig.json')
    await fs.writeFile(configFile, '{ invalid')

    await expect(writeTypesWorkspace(directory)).rejects.toThrow(/tsconfig\.json.*invalid/i)
    await expect(fs.readFile(configFile, 'utf8')).resolves.toBe('{ invalid')

    const linkedDirectory = await workspace()
    const targetDirectory = await workspace()
    const target = path.join(targetDirectory, 'tsconfig.json')
    await fs.writeFile(target, '{"compilerOptions":{}}')
    await fs.symlink(target, path.join(linkedDirectory, 'tsconfig.json'))

    await expect(writeTypesWorkspace(linkedDirectory)).rejects.toThrow(/tsconfig\.json.*symbolic link/i)
    await expect(fs.readFile(target, 'utf8')).resolves.toBe('{"compilerOptions":{}}')
  })

  it('rejects a symbolic-link output without changing its target', async () => {
    const directory = await workspace()
    const targetDirectory = await workspace()
    const target = path.join(targetDirectory, 'target.d.ts')
    const output = path.join(directory, DEFAULT_TYPES_FILENAME)
    await fs.writeFile(target, 'user content')
    await fs.symlink(target, output)

    await expect(writeTypesWorkspace(directory)).rejects.toThrow(/symbolic link/i)
    await expect(fs.readFile(target, 'utf8')).resolves.toBe('user content')
  })
})
