import path from 'node:path'
import { JSON_SCHEMA_RELATIVE_PATHS, type JsonSchemaName } from './names.js'

export type JsonSchema = Record<string, unknown>

const JSON_SCHEMA_DRAFT = 'http://json-schema.org/draft-07/schema#'

export const RESOURCE_IDENTIFIER_PATTERN = '^[A-Za-z0-9_-]{1,128}$'

export const WORKFLOW_VERSION_PATTERN = '^\\d{1,10}\\.\\d{1,10}$'

export const HEADER_NAME_PATTERN = "^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$"

export const stringValue = (): JsonSchema => ({ type: 'string' })

export const nonEmptyString = (): JsonSchema => ({ type: 'string', minLength: 1 })

export const nonBlankString = (): JsonSchema => ({ type: 'string', minLength: 1, pattern: '\\S' })

export const booleanValue = (): JsonSchema => ({ type: 'boolean' })

export const integer = (minimum?: number, maximum?: number): JsonSchema => ({
  type: 'integer',
  ...(minimum === undefined ? {} : { minimum }),
  ...(maximum === undefined ? {} : { maximum })
})

export const stringArray = (
  options: { maxItems?: number; minItems?: number; uniqueItems?: boolean } = {}
): JsonSchema => ({
  type: 'array',
  items: stringValue(),
  ...options
})

export const arrayOf = (
  items: JsonSchema,
  options: { maxItems?: number; minItems?: number; uniqueItems?: boolean } = {}
): JsonSchema => ({
  type: 'array',
  items,
  ...options
})

export const reference = (name: string): JsonSchema => ({ $ref: `#/definitions/${name}` })

export const object = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
  additionalProperties: boolean | JsonSchema = false
): JsonSchema => ({
  type: 'object',
  properties,
  ...(required.length === 0 ? {} : { required }),
  additionalProperties
})

export const arbitraryObject = (): JsonSchema => ({ type: 'object' })

export const nullableNumber = (constraints: JsonSchema = {}): JsonSchema => ({
  type: ['number', 'null'],
  ...constraints
})

const schemaProperty = (): JsonSchema => ({
  type: 'string',
  format: 'uri-reference',
  description: 'Local JSON Schema used by editors. The CLI treats this property as file metadata.'
})

export function rootSchema(
  name: JsonSchemaName,
  title: string,
  properties: Record<string, JsonSchema>,
  required: string[],
  definitions: Record<string, JsonSchema> = {}
): JsonSchema {
  return {
    $schema: JSON_SCHEMA_DRAFT,
    $id: path.posix.basename(JSON_SCHEMA_RELATIVE_PATHS[name]),
    $comment: 'Generated by the GHL CLI. Run `ghl app pull` to regenerate. Do not edit manually.',
    title,
    type: 'object',
    properties: { $schema: schemaProperty(), ...properties },
    required,
    additionalProperties: false,
    ...(Object.keys(definitions).length === 0 ? {} : { definitions })
  }
}
