import path from 'node:path'
import { JSON_SCHEMA_RELATIVE_PATHS, type JsonSchemaName } from './names.js'

export type JsonSchema = Record<string, unknown>

const JSON_SCHEMA_DRAFT = 'http://json-schema.org/draft-07/schema#'

export const RESOURCE_IDENTIFIER_PATTERN = '^[A-Za-z0-9_-]{1,128}$'

export const WORKFLOW_VERSION_PATTERN = '^\\d{1,10}\\.\\d{1,10}$'

export const HEADER_NAME_PATTERN = "^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$"

export const MAX_URL_LENGTH = 2_048

export const OAUTH_SCOPE_PATTERN = '^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,199}$'

export const WEBHOOK_EVENT_PATTERN = '^[a-zA-Z][a-zA-Z0-9._:-]{0,199}$'

export const stringValue = (constraints: JsonSchema = {}): JsonSchema => ({ type: 'string', ...constraints })

export const nonEmptyString = (constraints: JsonSchema = {}): JsonSchema => ({
  type: 'string',
  minLength: 1,
  pattern: '\\S',
  ...constraints
})

export const nonBlankString = (constraints: JsonSchema = {}): JsonSchema => ({
  type: 'string',
  minLength: 1,
  pattern: '\\S',
  ...constraints
})

export const booleanValue = (constraints: JsonSchema = {}): JsonSchema => ({ type: 'boolean', ...constraints })

export const integer = (minimum?: number, maximum?: number, constraints: JsonSchema = {}): JsonSchema => ({
  type: 'integer',
  ...(minimum === undefined ? {} : { minimum }),
  ...(maximum === undefined ? {} : { maximum }),
  ...constraints
})

export const stringArray = (
  options: { description?: string; maxItems?: number; minItems?: number; uniqueItems?: boolean } = {},
  items: JsonSchema = stringValue()
): JsonSchema => ({
  type: 'array',
  items,
  ...options
})

export const arrayOf = (
  items: JsonSchema,
  options: { description?: string; maxItems?: number; minItems?: number; uniqueItems?: boolean } = {}
): JsonSchema => ({
  type: 'array',
  items,
  ...options
})

export const reference = (name: string): JsonSchema => ({ $ref: `#/definitions/${name}` })

export const object = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
  additionalProperties: boolean | JsonSchema = false
): JsonSchema => ({
  type: 'object',
  properties,
  ...(required.length === 0 ? {} : { required }),
  additionalProperties
})

export const arbitraryObject = (): JsonSchema => ({ type: 'object' })

export const nullableNumber = (constraints: JsonSchema = {}): JsonSchema => ({
  type: ['number', 'null'],
  ...constraints
})

/* URL schemas check only the scheme. The RFC 3986 `uri` format rejects
   characters such as braces, brackets, and non-ASCII paths that the WHATWG
   parser used by the CLI validators accepts, so the full URL check stays with
   those validators. */
export const requiredHttpUrl = (description: string): JsonSchema =>
  nonBlankString({
    maxLength: MAX_URL_LENGTH,
    pattern: '^https?://',
    description
  })

export const requiredHttpsUrl = (description: string): JsonSchema =>
  nonBlankString({
    maxLength: MAX_URL_LENGTH,
    pattern: '^https://',
    description
  })

export const optionalHttpUrl = (description: string): JsonSchema => ({
  type: 'string',
  maxLength: MAX_URL_LENGTH,
  pattern: '^(?:$|https?://)',
  description
})

export const optionalHttpsUrl = (description: string): JsonSchema => ({
  type: 'string',
  maxLength: MAX_URL_LENGTH,
  pattern: '^(?:$|https://)',
  description
})

const schemaProperty = (): JsonSchema => ({
  type: 'string',
  description: 'Local JSON Schema used by editors. The CLI treats this property as file metadata.'
})

export function rootSchema(
  name: JsonSchemaName,
  title: string,
  properties: Record<string, JsonSchema>,
  required: string[],
  definitions: Record<string, JsonSchema> = {}
): JsonSchema {
  return {
    $schema: JSON_SCHEMA_DRAFT,
    $id: path.posix.basename(JSON_SCHEMA_RELATIVE_PATHS[name]),
    $comment: 'Generated by the GHL CLI. Run `ghl app types` to regenerate. Do not edit manually.',
    title,
    type: 'object',
    properties: { $schema: schemaProperty(), ...properties },
    required,
    additionalProperties: false,
    ...(Object.keys(definitions).length === 0 ? {} : { definitions })
  }
}
