export const BILLING_GUIDE_FILENAME = 'HIGHLEVEL_BILLING.md'

export function buildBillingGuide(): string {
  return [
    '# HighLevel app billing',
    '',
    'Billing settings that apply to the whole app remain in `ghl-app.json` under `billing`. Marketplace subscription plans and usage meters are app-level resources stored separately in this directory. External billing follows the portal eligibility cutoff and is unavailable for apps created after June 17, 2026.',
    '',
    '## Files',
    '',
    '- `subscription.json` contains marketplace subscription plans. It is omitted when the app has no plans.',
    '- `usage-based.json` contains usage meters and their pricing tiers. It is omitted when the app has no meters.',
    '- `.ghl/billing-state.json` is the last-pulled baseline used for conflict detection. Never edit it manually.',
    '',
    'Run `ghl app billing validate`, then `ghl app billing diff`, then `ghl app billing push`. A regular `ghl app pull` also refreshes billing resources.',
    '',
    '## Commands',
    '',
    '- `ghl app billing`: show remote billing settings, plans, and meters.',
    '- `ghl app billing pull`: refresh both source files and the private baseline.',
    '- `ghl app billing validate`: validate local files without authentication or API calls.',
    '- `ghl app billing diff`: merge the local, baseline, and current portal states and show exact API operations.',
    '- `ghl app billing push`: validate, apply only changed resources, verify, and reconcile local files.',
    '- `ghl app billing plan create|delete`: stage plan changes locally.',
    '- `ghl app billing meter create|delete`: stage usage-meter changes locally.',
    '',
    'Edit app-wide `billingType`, external-billing, and free-trial fields in `ghl-app.json`, then run `ghl app push`. Plan and meter changes are applied separately with `ghl app billing push`. If a model change is required before the plan API accepts the desired configuration, push `ghl-app.json` first.',
    '',
    '## Subscription schema',
    '',
    'The root keys are `schemaVersion`, `appId`, and `plans`. Each plan supports:',
    '',
    '- `id`: server-owned plan id. Omit it for a new plan.',
    '- `name`: customer-facing plan name.',
    '- `features`: up to five customer-facing feature strings.',
    '- `paymentTime`: `month`, `year`, or `life_time`.',
    '- `paymentType`: `recurring` for month/year or `one_time` for life_time.',
    '- `amount`: agency price in USD with at most two decimal places.',
    '- `locationAmount`: optional sub-account price in USD when both target types are enabled.',
    '- `freePlan`: marks the fully free plan of a freemium app.',
    '- `freeForAgency` and `freeForLocation`: make one install target free while charging the other.',
    '',
    'Example:',
    '',
    '```json',
    '{',
    '  "schemaVersion": 1,',
    '  "appId": "APP_ID",',
    '  "plans": [',
    '    {',
    '      "name": "Pro",',
    '      "features": ["Automation", "Analytics"],',
    '      "paymentTime": "month",',
    '      "paymentType": "recurring",',
    '      "amount": 49,',
    '      "locationAmount": 29,',
    '      "freePlan": false,',
    '      "freeForAgency": false,',
    '      "freeForLocation": false',
    '    }',
    '  ]',
    '}',
    '```',
    '',
    'After a plan is created, only `name` and `features` can be edited. Its `amount`, `paymentTime`, `paymentType`, location amount, and free flags are immutable; create a replacement plan to change them. Plans can be changed only from draft or disapproved app versions, with a maximum of six plans. Template apps support one life-time plan.',
    '',
    '## Usage-based schema',
    '',
    'The root keys are `schemaVersion`, `appId`, and `meters`. Each meter supports:',
    '',
    '- `id`: server-owned meter id. Omit it for a new meter.',
    '- `productType`: `conversation_provider`, `workflow_action`, `workflow_trigger`, or `custom`.',
    '- `productId`: provider id, workflow action/trigger key, or a stable custom id beginning with `custom_`.',
    '- `productName`: customer-facing product name.',
    '- `customPriceType`: `fixed`, or `dynamic` for custom products only.',
    '- `usageUnit`: `message` for providers, `execution` for workflows, or a custom unit of at most 19 characters.',
    '- `direction`: `inbound` or `outbound`; required only for conversation providers.',
    '- `pricingPageUrl`: public HTTPS pricing page; required only for dynamic pricing.',
    '- `tiers`: one or more non-overlapping volume ranges.',
    '',
    'Each tier supports `id`, `name`, `minVolume`, `maxVolume`, `pricePerUnit`, `executionLimitPerCycle`, and dynamic-pricing bounds `minPricePerUnit`/`maxPricePerUnit`. Use `null` for an unlimited `maxVolume`. Unit prices range from 0.000001 through 200 and allow at most six decimals.',
    '',
    'Example workflow-action meter:',
    '',
    '```json',
    '{',
    '  "schemaVersion": 1,',
    '  "appId": "APP_ID",',
    '  "meters": [',
    '    {',
    '      "productType": "workflow_action",',
    '      "productId": "send_contact_payload",',
    '      "productName": "Send contact payload",',
    '      "customPriceType": "fixed",',
    '      "usageUnit": "execution",',
    '      "tiers": [',
    '        {',
    '          "name": "Action executions",',
    '          "minVolume": 0,',
    '          "maxVolume": null,',
    '          "pricePerUnit": 0.01,',
    '          "executionLimitPerCycle": 10000',
    '        }',
    '      ]',
    '    }',
    '  ]',
    '}',
    '```',
    '',
    'Dynamic custom meters additionally set `customPriceType` to `dynamic`, provide `minPricePerUnit` and `maxPricePerUnit` on every tier, and provide `pricingPageUrl` on the meter. The default `pricePerUnit` must be inside the configured range.',
    '',
    'Workflow action and trigger meters must reference a component already registered remotely. Pull the matching component state first and push new actions/triggers before staging a meter; billing validation checks both the local key and the last synchronized component baseline.',
    '',
    'Meter `productType`, `productId`, `direction`, and `customPriceType` are immutable after creation. Usage meters are app-level and can be managed for live apps, matching the developer portal. They are unavailable for template apps or apps using external billing.',
    '',
    '## App versions',
    '',
    'Subscription plans and usage meters are addressed by `appId`, so separate copies are not created per app version. Subscription mutations use the workspace-bound version status for portal parity; create a draft before changing plans on a live or review-locked version. Usage meters remain editable for live apps. Workflow meter `productId` values are stable action/trigger keys rather than module version ids.',
    '',
    '## Conflict behavior',
    '',
    'Push compares local JSON, the last pull, and the current portal state. Non-overlapping edits are merged. Overlapping edits, unknown server ids, and edits to immutable fields stop before any mutation API call. Deletions require `--force` when non-interactive. Each independent operation is reported separately; successful operations are verified and failed local intent remains staged for retry.',
    ''
  ].join('\n')
}
