export const GENERATED_FILE_MARKER = 'Auto generated by @gohighlevel/marketplace-cli'
export const LEGACY_GENERATED_FILE_MARKER = 'Generated by @gohighlevel/marketplace-cli'

export function generatedFileHeader(...details: string[]): string {
  return [
    '/*',
    ` * ${GENERATED_FILE_MARKER}`,
    ...details.map(detail => ` * ${detail}`),
    ' * Run `ghl app types` to regenerate. Do not edit manually.',
    ' */'
  ].join('\n')
}

export function hasGeneratedFileMarker(contents: string): boolean {
  return contents.includes(GENERATED_FILE_MARKER) || contents.includes(LEGACY_GENERATED_FILE_MARKER)
}
