import { promises as fs } from 'node:fs'
import path from 'node:path'

import { writeTextFileAtomic } from '../../shared/atomic-file.js'
import { removeEmptyDirectoryTree } from '../../shared/workspace-files.js'
import { workflowActionCodeFilename } from './code.js'
import type {
  WorkflowActionDefinition,
  WorkflowActionInput,
  WorkflowActionVersion,
  WorkflowActionsManifest
} from './manifest.js'

export const WORKFLOW_ACTION_TYPES_RELATIVE_DIRECTORY = path.join('.ghl', 'types', 'actions')
export const WORKFLOW_ACTION_SANDBOX_TYPES_FILENAME = 'sandbox.d.ts'
export const WORKFLOW_ACTION_TYPESCRIPT_CONFIG_FILENAME = 'tsconfig.json'
const WORKFLOW_ACTION_TYPESCRIPT_CONFIG_RELATIVE_DIRECTORY = path.join('src', 'modules', 'workflows', 'actions', 'code')

const GENERATED_MARKER = 'Generated by @gohighlevel/marketplace-cli'
const ACTION_TYPES_PATTERN = /^[a-z][_a-z0-9]*\.d\.ts$/
const LEGACY_ACTION_TYPES_PATTERN = /^ghl-action-[a-z][_a-z0-9]*\.d\.ts$/
const LEGACY_SANDBOX_TYPES_FILENAME = 'ghl-action-sandbox.d.ts'
const WORKFLOW_ACTION_CODE_RELATIVE_DIRECTORY = path.join('src', 'modules', 'workflows', 'actions', 'code')

export interface WorkflowActionTypesWorkspaceResult {
  sandboxDeclarationFile: string
  actionDeclarationFiles: string[]
  typescriptConfigFile: string
}

export interface WorkflowActionTypeOptions {
  generatedAt?: Date
}

function generatedHeader(generatedAt: Date, source?: string): string {
  if (Number.isNaN(generatedAt.getTime())) throw new Error('Generated-at timestamp must be a valid date.')
  return [
    '/*',
    ` * ${GENERATED_MARKER} on ${generatedAt.toISOString()}.`,
    ...(source ? [` * Source: ${source}.`] : []),
    ' * Run `ghl app types` to regenerate. Do not edit manually.',
    ' */'
  ].join('\n')
}

function pascalCase(value: string): string {
  const result = value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map(part => part[0].toUpperCase() + part.slice(1))
    .join('')
  return result || 'Action'
}

function versionIdentifier(version: string): string {
  return `V${version.replaceAll('.', '_')}`
}

export function workflowActionVersionTypePrefix(key: string, version: string): string {
  return `GhlAction${pascalCase(key)}${versionIdentifier(version)}`
}

export function workflowActionTypeFilename(key: string): string {
  return `${key}.d.ts`
}

function stringLiteral(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n').replaceAll('\r', '\\r')}'`
}

function optionType(input: WorkflowActionInput): string {
  const values = input.options?.map(option => option.value).filter((value, index, all) => all.indexOf(value) === index)
  return values && values.length > 0 ? values.map(stringLiteral).join(' | ') : 'string'
}

function inputType(input: WorkflowActionInput): string {
  switch (input.fieldType) {
    case 'numerical':
      return 'number | string'
    case 'checkbox':
    case 'toggle':
      return 'boolean | string'
    case 'select':
    case 'radio':
    case 'select_with_pagination':
      return optionType(input)
    case 'multiselect':
    case 'multiselect_with_pagination':
    case 'tags':
      return `ReadonlyArray<${optionType(input)}>`
    case 'key-value':
      return 'Readonly<Record<string, string>>'
    case 'fieldSet':
      return 'ReadonlyArray<Readonly<Record<string, unknown>>>'
    case 'attachment':
      return 'ReadonlyArray<unknown> | string'
    case 'DYNAMIC':
    case 'custom-html':
      return 'unknown'
    default:
      return 'string'
  }
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value)
}

function cleanDescription(value: string): string {
  return value.replaceAll('*/', '* /').replace(/\s+/g, ' ').trim()
}

function inputDescription(input: WorkflowActionInput): string[] {
  const summary = [input.required === true ? 'Required.' : 'Optional.', input.title]
  if (input.helpText?.trim()) summary.push(cleanDescription(input.helpText))
  if (input.validations?.length) {
    summary.push(`Validation: ${input.validations.map(validation => validation.rule).join(', ')}.`)
  }
  return ['  /**', `   * ${cleanDescription(summary.join(' '))}`, '   */']
}

function renderDataType(action: WorkflowActionDefinition, version: WorkflowActionVersion): string {
  const name = `${workflowActionVersionTypePrefix(action.key, version.version)}Data`
  const inputs = version.inputs ?? []
  const dynamic = inputs.some(input => input.field === 'DYNAMIC' || input.fieldType === 'DYNAMIC')
  const properties = inputs.flatMap(input => {
    if (input.field === 'DYNAMIC' || input.fieldType === 'DYNAMIC') return []
    return [
      ...inputDescription(input),
      `  readonly ${propertyName(input.field)}${input.required === true ? '' : '?'}: ${inputType(input)};`
    ]
  })
  const object = properties.length > 0 ? ['{', ...properties, '}'].join('\n') : 'Readonly<Record<string, never>>'
  const rendered = dynamic
    ? properties.length > 0
      ? `Readonly<Record<string, unknown>> & ${object}`
      : 'Readonly<Record<string, unknown>>'
    : object
  return `export type ${name} = ${rendered};`
}

function renderJsonType(value: unknown, level: number): string {
  if (value === null) return 'null'
  if (typeof value === 'string') return 'string'
  if (typeof value === 'number') return 'number'
  if (typeof value === 'boolean') return 'boolean'
  if (Array.isArray(value)) {
    if (value.length === 0) return 'ReadonlyArray<unknown>'
    const itemTypes = [...new Set(value.map(item => renderJsonType(item, level)))]
    return `ReadonlyArray<${itemTypes.join(' | ')}>`
  }
  if (typeof value !== 'object' || value === undefined) return 'unknown'
  const entries = Object.entries(value)
  if (entries.length === 0) return 'Readonly<Record<string, unknown>>'
  const indentation = '  '.repeat(level)
  return [
    '{',
    ...entries.map(
      ([key, child]) => `${'  '.repeat(level + 1)}readonly ${propertyName(key)}: ${renderJsonType(child, level + 1)};`
    ),
    `${indentation}}`
  ].join('\n')
}

function renderOutputType(action: WorkflowActionDefinition, version: WorkflowActionVersion): string {
  const name = `${workflowActionVersionTypePrefix(action.key, version.version)}Output`
  const output = version.customVarsJson
  if (output && !Array.isArray(output) && Object.keys(output).length > 0) {
    return `export interface ${name} ${renderJsonType(output, 0)}`
  }
  return `export type ${name} = GhlActionOutput;`
}

export function generateWorkflowActionDeclaration(action: WorkflowActionDefinition, generatedAt = new Date()): string {
  const declarations = action.versions.flatMap(version => {
    const prefix = workflowActionVersionTypePrefix(action.key, version.version)
    return [
      renderDataType(action, version),
      renderOutputType(action, version),
      `export type ${prefix}Handler = GhlActionHandler<${prefix}Data, ${prefix}Output>;`
    ]
  })
  return `${generatedHeader(generatedAt, `${action.key}.json`)}\n\nimport type { GhlActionHandler, GhlActionOutput } from './sandbox'\n\n${declarations.join('\n\n')}\n`
}

export function generateWorkflowActionSandboxDeclarations(generatedAt = new Date()): string {
  return `${generatedHeader(generatedAt)}

/**
 * Public contract for the GHL marketplace workflow-action sandbox.
 * The runtime is an isolated V8 context with an 8.1 MiB heap and 60 second execution limit.
 */
export type GhlJsonPrimitive = boolean | number | string | null;
export type GhlJsonValue = GhlJsonPrimitive | ReadonlyArray<GhlJsonValue> | { readonly [key: string]: GhlJsonValue };
export type GhlActionOutput = object;

export interface GhlActionBranch {
  readonly id: string;
  readonly name: string;
  readonly fields: Readonly<Record<string, unknown>>;
  readonly meta?: Readonly<Record<string, unknown>>;
}

export interface GhlActionExtras {
  readonly locationId?: string;
  readonly companyId?: string;
  readonly contactId?: string;
  readonly workflowId?: string;
  readonly stepIndex?: number;
  readonly stepId?: string;
  readonly statusId?: string;
  readonly actionId?: string;
}

export interface GhlActionInputData<TData extends Readonly<Record<string, unknown>>> {
  readonly data: TData & { readonly branches?: ReadonlyArray<GhlActionBranch> };
  readonly extras: GhlActionExtras;
  readonly headers: Readonly<Record<string, string>>;
  readonly queryParams: Readonly<Record<string, string>>;
  readonly fields: Readonly<Record<string, unknown>>;
}

export interface GhlCustomRequestOptions {
  readonly data?: unknown;
  readonly headers?: Readonly<Record<string, string | number | boolean>>;
  readonly params?: Readonly<Record<string, unknown>>;
}

export interface GhlCustomRequestResponse<T = unknown> {
  readonly data: T;
  readonly status: number;
  readonly headers: Readonly<Record<string, unknown>>;
}

export interface GhlCustomRequest {
  get<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  post<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  put<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  delete<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  patch<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  head<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
  options<T = unknown>(url: string, options?: GhlCustomRequestOptions): Promise<GhlCustomRequestResponse<T>>;
}

export interface GhlConsole {
  log(...values: unknown[]): void;
  info(...values: unknown[]): void;
  warn(...values: unknown[]): void;
  error(...values: unknown[]): void;
  debug(...values: unknown[]): void;
}

export type GhlPropertyPath = string | ReadonlyArray<string | number>;
export type GhlIteratee<T, R = unknown> = ((value: T, index: number, collection: ReadonlyArray<T>) => R) | string;

export interface GhlLodash {
  chunk<T>(array: ReadonlyArray<T>, size?: number): T[][];
  compact<T>(array: ReadonlyArray<T | false | null | undefined | 0 | ''>): T[];
  concat<T>(...arrays: ReadonlyArray<T>[]): T[];
  difference<T>(array: ReadonlyArray<T>, ...values: ReadonlyArray<T>[]): T[];
  flatten<T>(array: ReadonlyArray<ReadonlyArray<T> | T>): T[];
  flattenDeep<T>(array: ReadonlyArray<unknown>): T[];
  uniq<T>(array: ReadonlyArray<T>): T[];
  zip<T>(...arrays: ReadonlyArray<T>[]): Array<Array<T | undefined>>;
  unzip<T>(array: ReadonlyArray<ReadonlyArray<T>>): T[][];
  intersection<T>(...arrays: ReadonlyArray<T>[]): T[];
  union<T>(...arrays: ReadonlyArray<T>[]): T[];
  pull<T>(array: ReadonlyArray<T>, ...values: T[]): T[];
  shuffle<T>(array: ReadonlyArray<T>): T[];
  reverse<T>(array: ReadonlyArray<T>): T[];
  sum(array: ReadonlyArray<number>): number;
  sumBy<T>(array: ReadonlyArray<T>, iteratee: GhlIteratee<T, number>): number;
  max(array: ReadonlyArray<number>): number | undefined;
  min(array: ReadonlyArray<number>): number | undefined;
  mean(array: ReadonlyArray<number>): number;
  meanBy<T>(array: ReadonlyArray<T>, iteratee: GhlIteratee<T, number>): number;
  get<T = unknown, D = undefined>(object: unknown, path: GhlPropertyPath, defaultValue?: D): T | D;
  set<T extends object>(object: T, path: GhlPropertyPath, value: unknown): T;
  has(object: unknown, path: GhlPropertyPath): boolean;
  merge(...objects: ReadonlyArray<object>): Record<string, unknown>;
  pick<T extends object>(object: T, paths: ReadonlyArray<string>): Partial<T>;
  omit<T extends object>(object: T, paths: ReadonlyArray<string>): Partial<T>;
  keys(object: object): string[];
  values<T>(object: Readonly<Record<string, T>>): T[];
  map<T, R>(collection: ReadonlyArray<T>, iteratee: (value: T, index: number) => R): R[];
  filter<T>(collection: ReadonlyArray<T>, predicate: ((value: T, index: number) => boolean) | Partial<T>): T[];
  find<T>(collection: ReadonlyArray<T>, predicate: ((value: T, index: number) => boolean) | Partial<T>): T | undefined;
  reduce<T, R>(collection: ReadonlyArray<T>, iteratee: (accumulator: R, value: T, index: number) => R, initial: R): R;
  groupBy<T>(collection: ReadonlyArray<T>, iteratee: GhlIteratee<T, string | number>): Record<string, T[]>;
  sortBy<T>(collection: ReadonlyArray<T>, iteratees?: GhlIteratee<T> | ReadonlyArray<GhlIteratee<T>>): T[];
  orderBy<T>(collection: ReadonlyArray<T>, iteratees?: GhlIteratee<T> | ReadonlyArray<GhlIteratee<T>>, orders?: ReadonlyArray<'asc' | 'desc'>): T[];
  isEqual(left: unknown, right: unknown): boolean;
  isObject(value: unknown): value is object;
  isArray(value: unknown): value is unknown[];
  isString(value: unknown): value is string;
  isNumber(value: unknown): value is number;
  isBoolean(value: unknown): value is boolean;
  isEmpty(value: unknown): boolean;
  cloneDeep<T>(value: T): T;
}

export type GhlMomentUnit = 'year' | 'years' | 'month' | 'months' | 'week' | 'weeks' | 'day' | 'days' | 'hour' | 'hours' | 'minute' | 'minutes' | 'second' | 'seconds' | 'millisecond' | 'milliseconds';
export type GhlMomentInput = Date | GhlMomentValue | ReadonlyArray<number> | number | string | undefined;

export interface GhlMomentDuration {
  asMilliseconds(): number;
  asSeconds(): number;
  asMinutes(): number;
  asHours(): number;
  asDays(): number;
  asWeeks(): number;
  asMonths(): number;
  asYears(): number;
  milliseconds(): number;
  seconds(): number;
  minutes(): number;
  hours(): number;
  days(): number;
  weeks(): number;
  months(): number;
  years(): number;
}

export interface GhlMomentValue {
  format(format?: string): string;
  add(amount: number, unit: GhlMomentUnit): GhlMomentValue;
  subtract(amount: number, unit: GhlMomentUnit): GhlMomentValue;
  startOf(unit: GhlMomentUnit): GhlMomentValue;
  endOf(unit: GhlMomentUnit): GhlMomentValue;
  local(): GhlMomentValue;
  utc(): GhlMomentValue;
  clone(): GhlMomentValue;
  tz(timezone: string): GhlMomentValue;
  year(): number;
  year(value: number): GhlMomentValue;
  month(): number;
  month(value: number): GhlMomentValue;
  date(): number;
  date(value: number): GhlMomentValue;
  day(): number;
  day(value: number): GhlMomentValue;
  hour(): number;
  hour(value: number): GhlMomentValue;
  minute(): number;
  minute(value: number): GhlMomentValue;
  second(): number;
  second(value: number): GhlMomentValue;
  millisecond(): number;
  millisecond(value: number): GhlMomentValue;
  valueOf(): number;
  unix(): number;
  toISOString(): string;
  isValid(): boolean;
  locale(): string;
  locale(value: string): GhlMomentValue;
}

export interface GhlMomentFactory {
  (input?: GhlMomentInput, format?: string | ReadonlyArray<string>, strict?: boolean): GhlMomentValue;
  utc(input?: GhlMomentInput, format?: string | ReadonlyArray<string>): GhlMomentValue;
  tz(input: GhlMomentInput, timezone: string): GhlMomentValue;
  tz(input: GhlMomentInput, format: string | ReadonlyArray<string>, timezone: string): GhlMomentValue;
  tz(input: GhlMomentInput, format: string | ReadonlyArray<string>, strict: boolean, timezone: string): GhlMomentValue;
  isValid(input: GhlMomentInput): boolean;
  duration(input?: number | Readonly<Record<string, number>>, unit?: GhlMomentUnit): GhlMomentDuration;
}

export interface GhlCsvOptions {
  readonly delimiter?: string;
  readonly headers?: ReadonlyArray<string>;
}

export interface GhlCsv {
  parse<T extends Readonly<Record<string, string>> = Readonly<Record<string, string>>>(csv: string, options?: GhlCsvOptions): T[];
  stringify(data: ReadonlyArray<Readonly<Record<string, unknown>>>, options?: GhlCsvOptions): string;
}

export interface GhlBase64 {
  encode(value: string): string;
  decode(value: string): string;
  encodeUrl(value: string): string;
  decodeUrl(value: string): string;
  isValid(value: string): boolean;
}

export type GhlUuidNamespace = 'DNS' | 'URL' | 'OID' | 'X500' | string;

export interface GhlUuid {
  v4(): string;
  v5(name: string, namespace: GhlUuidNamespace): string;
  validate(value: string): boolean;
  version(value: string): number;
  readonly NIL: '00000000-0000-0000-0000-000000000000';
}

export interface GhlFileTransferOptions {
  readonly downloadUrl: string;
  readonly formDataKey: string;
  readonly uploadUrl: string;
  readonly filename: string;
  readonly headers?: Readonly<Record<string, string | number | boolean>>;
}

export interface GhlFileDownloader {
  downloadAndUploadFormData<T = unknown>(options: GhlFileTransferOptions): Promise<GhlCustomRequestResponse<T>>;
}

export interface GhlActionContext<TData extends Readonly<Record<string, unknown>>> {
  readonly inputData: GhlActionInputData<TData>;
  readonly customRequest: GhlCustomRequest;
  readonly console: GhlConsole;
  readonly _: GhlLodash;
  readonly moment: GhlMomentFactory;
  readonly fileDownloader: GhlFileDownloader;
  readonly _csv: GhlCsv;
  readonly _base64: GhlBase64;
  readonly _uuid: GhlUuid;
}

export type GhlActionHandler<
  TData extends Readonly<Record<string, unknown>>,
  TOutput extends GhlActionOutput
> = (context: GhlActionContext<TData>) => TOutput | Promise<TOutput>;

/**
 * Not exposed by the sandbox: fetch, crypto, timers, URL, URLSearchParams,
 * TextEncoder, TextDecoder, atob, btoa, process, require, Buffer, and module imports.
 */
`
}

function actionTypeScriptConfig(): string {
  const config = {
    compilerOptions: {
      exactOptionalPropertyTypes: true,
      lib: ['ES2022'],
      module: 'ESNext',
      moduleDetection: 'force',
      moduleResolution: 'Bundler',
      noEmit: true,
      noUncheckedIndexedAccess: true,
      skipLibCheck: false,
      strict: true,
      target: 'ES2022',
      types: []
    },
    include: ['../../../../../.ghl/types/actions/*.d.ts', '*.ts']
  }
  return `/* ${GENERATED_MARKER}. Do not edit manually. */\n${JSON.stringify(config, null, 2)}\n`
}

async function lstatIfPresent(target: string): Promise<Awaited<ReturnType<typeof fs.lstat>> | undefined> {
  try {
    return await fs.lstat(target)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

async function assertGeneratedFileWritable(file: string): Promise<void> {
  const stat = await lstatIfPresent(file)
  if (!stat) return
  if (stat.isSymbolicLink()) throw new Error(`Generated action type file "${file}" cannot be a symbolic link.`)
  if (!stat.isFile()) throw new Error(`Generated action type path "${file}" is not a regular file.`)
  const contents = await fs.readFile(file, 'utf8')
  if (!contents.includes(GENERATED_MARKER)) {
    throw new Error(`Action type file "${file}" is developer-owned and will not be overwritten.`)
  }
}

async function migrateLegacyActionTypeImports(directory: string, manifest: WorkflowActionsManifest): Promise<void> {
  await Promise.all(
    manifest.actions.flatMap(action =>
      action.versions.map(async version => {
        const file = path.join(
          directory,
          WORKFLOW_ACTION_CODE_RELATIVE_DIRECTORY,
          workflowActionCodeFilename(action.key, version.version, 'typescript')
        )
        const stat = await lstatIfPresent(file)
        if (!stat) return
        if (stat.isSymbolicLink()) throw new Error(`Workflow action code file "${file}" cannot be a symbolic link.`)
        if (!stat.isFile()) throw new Error(`Workflow action code path "${file}" is not a regular file.`)
        const source = await fs.readFile(file, 'utf8')
        const legacySpecifier = `../../../../../ghl-action-${action.key}`
        const nextSpecifier = `../../../../../.ghl/types/actions/${action.key}`
        const migrated = source
          .replaceAll(`from '${legacySpecifier}'`, `from '${nextSpecifier}'`)
          .replaceAll(`from "${legacySpecifier}"`, `from "${nextSpecifier}"`)
        if (migrated !== source) await writeTextFileAtomic(file, migrated, Number(stat.mode) & 0o777)
      })
    )
  )
}

function workflowActionTypeWorkspacePaths(
  inputDirectory: string,
  manifest: WorkflowActionsManifest
): WorkflowActionTypesWorkspaceResult {
  const directory = path.resolve(inputDirectory)
  const typesDirectory = path.join(directory, WORKFLOW_ACTION_TYPES_RELATIVE_DIRECTORY)
  return {
    sandboxDeclarationFile: path.join(typesDirectory, WORKFLOW_ACTION_SANDBOX_TYPES_FILENAME),
    typescriptConfigFile: path.join(
      directory,
      WORKFLOW_ACTION_TYPESCRIPT_CONFIG_RELATIVE_DIRECTORY,
      WORKFLOW_ACTION_TYPESCRIPT_CONFIG_FILENAME
    ),
    actionDeclarationFiles: manifest.actions.map(action =>
      path.join(typesDirectory, workflowActionTypeFilename(action.key))
    )
  }
}

async function assertGeneratedDirectoryPathSafe(directory: string): Promise<void> {
  let current = directory
  for (const part of WORKFLOW_ACTION_TYPES_RELATIVE_DIRECTORY.split(path.sep)) {
    current = path.join(current, part)
    const stat = await lstatIfPresent(current)
    if (!stat) continue
    if (stat.isSymbolicLink())
      throw new Error(`Generated action type directory "${current}" cannot be a symbolic link.`)
    if (!stat.isDirectory()) throw new Error(`Generated action type path "${current}" is not a directory.`)
  }
}

export async function assertWorkflowActionTypesWorkspaceWritable(
  inputDirectory: string,
  manifest: WorkflowActionsManifest
): Promise<void> {
  const directory = path.resolve(inputDirectory)
  const files = workflowActionTypeWorkspacePaths(inputDirectory, manifest)
  await Promise.all([
    assertGeneratedDirectoryPathSafe(directory),
    ...[files.sandboxDeclarationFile, files.typescriptConfigFile, ...files.actionDeclarationFiles].map(
      assertGeneratedFileWritable
    )
  ])
}

export async function writeWorkflowActionTypesWorkspace(
  inputDirectory: string,
  manifest: WorkflowActionsManifest,
  options: WorkflowActionTypeOptions = {}
): Promise<WorkflowActionTypesWorkspaceResult> {
  const directory = path.resolve(inputDirectory)
  const generatedAt = options.generatedAt ?? new Date()
  const { sandboxDeclarationFile, typescriptConfigFile, actionDeclarationFiles } = workflowActionTypeWorkspacePaths(
    directory,
    manifest
  )
  await assertWorkflowActionTypesWorkspaceWritable(directory, manifest)
  const typesDirectory = path.dirname(sandboxDeclarationFile)
  await Promise.all([
    fs.mkdir(typesDirectory, { recursive: true, mode: 0o755 }),
    fs.mkdir(path.dirname(typescriptConfigFile), { recursive: true, mode: 0o755 })
  ])
  await Promise.all([
    writeTextFileAtomic(sandboxDeclarationFile, generateWorkflowActionSandboxDeclarations(generatedAt), 0o644),
    writeTextFileAtomic(typescriptConfigFile, actionTypeScriptConfig(), 0o644),
    ...manifest.actions.map((action, index) =>
      writeTextFileAtomic(actionDeclarationFiles[index], generateWorkflowActionDeclaration(action, generatedAt), 0o644)
    )
  ])
  await migrateLegacyActionTypeImports(directory, manifest)

  const desired = new Set(actionDeclarationFiles.map(file => path.basename(file)))
  const entries = await fs.readdir(typesDirectory, { withFileTypes: true })
  await Promise.all(
    entries
      .filter(
        entry =>
          entry.isFile() &&
          entry.name !== WORKFLOW_ACTION_SANDBOX_TYPES_FILENAME &&
          ACTION_TYPES_PATTERN.test(entry.name) &&
          !desired.has(entry.name)
      )
      .map(entry => removeGeneratedFile(path.join(typesDirectory, entry.name)))
  )
  const rootEntries = await fs.readdir(directory, { withFileTypes: true })
  await Promise.all(
    rootEntries
      .filter(
        entry =>
          entry.isFile() &&
          (entry.name === LEGACY_SANDBOX_TYPES_FILENAME || LEGACY_ACTION_TYPES_PATTERN.test(entry.name))
      )
      .map(entry => removeGeneratedFile(path.join(directory, entry.name)))
  )
  return { sandboxDeclarationFile, actionDeclarationFiles, typescriptConfigFile }
}

async function removeGeneratedFile(file: string): Promise<void> {
  const stat = await lstatIfPresent(file)
  if (!stat) return
  if (stat.isSymbolicLink() || !stat.isFile()) return
  const contents = await fs.readFile(file, 'utf8')
  if (contents.includes(GENERATED_MARKER)) await fs.unlink(file)
}

export async function removeWorkflowActionTypesWorkspace(inputDirectory: string): Promise<void> {
  const directory = path.resolve(inputDirectory)
  const typesDirectory = path.join(directory, WORKFLOW_ACTION_TYPES_RELATIVE_DIRECTORY)
  const typesDirectoryStat = await lstatIfPresent(typesDirectory)
  const entries = typesDirectoryStat?.isDirectory() ? await fs.readdir(typesDirectory, { withFileTypes: true }) : []
  const declarationFiles = entries
    .filter(
      entry =>
        entry.isFile() &&
        (entry.name === WORKFLOW_ACTION_SANDBOX_TYPES_FILENAME || ACTION_TYPES_PATTERN.test(entry.name))
    )
    .map(entry => path.join(typesDirectory, entry.name))
  const rootEntries = await fs.readdir(directory, { withFileTypes: true })
  const legacyDeclarationFiles = rootEntries
    .filter(
      entry =>
        entry.isFile() && (entry.name === LEGACY_SANDBOX_TYPES_FILENAME || LEGACY_ACTION_TYPES_PATTERN.test(entry.name))
    )
    .map(entry => path.join(directory, entry.name))
  const configFile = path.join(
    directory,
    WORKFLOW_ACTION_TYPESCRIPT_CONFIG_RELATIVE_DIRECTORY,
    WORKFLOW_ACTION_TYPESCRIPT_CONFIG_FILENAME
  )
  await Promise.all([...declarationFiles, ...legacyDeclarationFiles, configFile].map(removeGeneratedFile))
  if (typesDirectoryStat?.isDirectory()) await removeEmptyDirectoryTree(typesDirectory, directory)
}
