import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import ts from 'typescript'
import { afterEach, describe, expect, it } from 'vitest'

import type { WorkflowActionDefinition } from '../../../../src/lib/workflows/actions/manifest.js'
import {
  generateWorkflowActionDeclaration,
  generateWorkflowActionSandboxDeclarations,
  workflowActionTypeFilename,
  writeWorkflowActionTypesWorkspace
} from '../../../../src/lib/workflows/actions/types.js'
import { generateWorkflowActionTypeScriptScaffold } from '../../../../src/lib/workflows/actions/typescript.js'

const GENERATED_AT = new Date('2026-09-15T09:30:00.000Z')
const directories: string[] = []

afterEach(async () => {
  await Promise.all(directories.splice(0).map(directory => fs.rm(directory, { force: true, recursive: true })))
})

function diagnostics(files: Record<string, string>): readonly ts.Diagnostic[] {
  const options: ts.CompilerOptions = {
    lib: ['lib.es2022.d.ts'],
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    types: []
  }
  const normalized = new Map(Object.entries(files).map(([file, contents]) => [path.resolve(file), contents]))
  const host = ts.createCompilerHost(options)
  const directoryExists = host.directoryExists?.bind(host)
  const getSourceFile = host.getSourceFile.bind(host)
  const fileExists = host.fileExists.bind(host)
  const readFile = host.readFile.bind(host)
  const virtualDirectories = new Set([...normalized.keys()].map(file => path.dirname(file)))
  host.directoryExists = directory =>
    virtualDirectories.has(path.resolve(directory)) || directoryExists?.(directory) === true
  host.fileExists = file => normalized.has(path.resolve(file)) || fileExists(file)
  host.readFile = file => normalized.get(path.resolve(file)) ?? readFile(file)
  host.getSourceFile = (file, languageVersion, onError, shouldCreateNewSourceFile) => {
    const contents = normalized.get(path.resolve(file))
    return contents === undefined
      ? getSourceFile(file, languageVersion, onError, shouldCreateNewSourceFile)
      : ts.createSourceFile(file, contents, languageVersion, true)
  }
  return ts.getPreEmitDiagnostics(ts.createProgram([...normalized.keys()], options, host))
}

function action(): WorkflowActionDefinition {
  return {
    key: 'calculate_score',
    versions: [
      {
        version: '1.0',
        status: 'draft',
        info: { name: 'Calculate score' },
        inputs: [
          {
            field: 'score',
            title: 'Score',
            fieldType: 'numerical',
            required: true,
            helpText: 'Numeric score supplied by the workflow.'
          },
          {
            field: 'mode',
            title: 'Mode',
            fieldType: 'select',
            options: [
              { label: 'Safe', value: 'safe' },
              { label: 'Fast', value: 'fast' }
            ]
          },
          {
            field: 'labels',
            title: 'Labels',
            fieldType: 'multiselect',
            options: [
              { label: 'Lead', value: 'lead' },
              { label: 'Customer', value: 'customer' }
            ]
          },
          { field: 'DYNAMIC', title: 'Dynamic fields', fieldType: 'DYNAMIC' }
        ],
        customVarsJson: {
          result: { accepted: true, total: 42, labels: ['lead'] },
          requestId: 'req-1'
        }
      }
    ]
  }
}

describe('workflow action TypeScript declarations', () => {
  it('describes the verified sandbox surface without advertising unavailable APIs', () => {
    const declaration = generateWorkflowActionSandboxDeclarations(GENERATED_AT)

    expect(declaration).toMatch(/Generated by @gohighlevel\/marketplace-cli on 2026-09-15T09:30:00\.000Z/)
    expect(declaration).toContain('export interface GhlCustomRequest')
    expect(declaration).toContain('readonly customRequest: GhlCustomRequest')
    expect(declaration).toContain('readonly _: GhlLodash')
    expect(declaration).toContain('readonly moment: GhlMomentFactory')
    expect(declaration).toContain('readonly fileDownloader: GhlFileDownloader')
    expect(declaration).toContain('readonly _csv: GhlCsv')
    expect(declaration).toContain('readonly _base64: GhlBase64')
    expect(declaration).toContain('readonly _uuid: GhlUuid')
    expect(declaration).not.toMatch(
      /declare\s+(?:const|function)\s+(?:fetch|crypto|setTimeout|URL|process|require|Buffer)\b/
    )
    expect(declaration).not.toContain('timeout?:')
    expect(diagnostics({ '/virtual/ghl-action-sandbox.d.ts': declaration })).toEqual([])
  })

  it('derives versioned input and output types from the action manifest', () => {
    const declaration = generateWorkflowActionDeclaration(action(), GENERATED_AT)

    expect(workflowActionTypeFilename('calculate_score')).toBe('ghl-action-calculate_score.d.ts')
    expect(declaration).toContain('export type GhlActionCalculateScoreV1_0Data =')
    expect(declaration).toContain('Readonly<Record<string, unknown>> &')
    expect(declaration).toContain('readonly score: number | string;')
    expect(declaration).toContain("readonly mode?: 'safe' | 'fast';")
    expect(declaration).toContain("readonly labels?: ReadonlyArray<'lead' | 'customer'>;")
    expect(declaration).toContain('export interface GhlActionCalculateScoreV1_0Output')
    expect(declaration).toContain('readonly accepted: boolean;')
    expect(declaration).toContain('readonly total: number;')
    expect(declaration).toContain('export type GhlActionCalculateScoreV1_0Handler = GhlActionHandler<')
    expect(
      diagnostics({
        '/virtual/ghl-action-sandbox.d.ts': generateWorkflowActionSandboxDeclarations(GENERATED_AT),
        '/virtual/ghl-action-calculate_score.d.ts': declaration
      })
    ).toEqual([])
  })

  it('keeps a dynamic-only input map open to runtime-defined fields', () => {
    const definition = action()
    definition.versions[0].inputs = [{ field: 'DYNAMIC', title: 'Dynamic fields', fieldType: 'DYNAMIC' }]

    const declaration = generateWorkflowActionDeclaration(definition, GENERATED_AT)

    expect(declaration).toContain('export type GhlActionCalculateScoreV1_0Data = Readonly<Record<string, unknown>>;')
    expect(declaration).not.toContain('Readonly<Record<string, unknown>> & Readonly<Record<string, never>>')
  })

  it('writes an isolated editor project that rejects unavailable browser globals', async () => {
    const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'ghl-action-types-'))
    directories.push(directory)
    const definition = action()
    const generated = await writeWorkflowActionTypesWorkspace(
      directory,
      { schemaVersion: 1, appId: 'app-1', actions: [definition] },
      { generatedAt: GENERATED_AT }
    )
    const codeFile = path.join(directory, 'src/modules/workflows/actions/code/calculate_score.1.0.ts')
    await fs.writeFile(codeFile, generateWorkflowActionTypeScriptScaffold(definition, definition.versions[0]))
    const parsed = ts.getParsedCommandLineOfConfigFile(
      generated.typescriptConfigFile,
      {},
      {
        ...ts.sys,
        onUnRecoverableConfigFileDiagnostic: diagnostic => {
          throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))
        }
      }
    )
    expect(parsed).toBeDefined()
    expect(ts.getPreEmitDiagnostics(ts.createProgram(parsed?.fileNames ?? [], parsed?.options ?? {}))).toEqual([])

    await fs.appendFile(codeFile, '\nvoid fetch\n')
    const invalid = ts.getParsedCommandLineOfConfigFile(
      generated.typescriptConfigFile,
      {},
      {
        ...ts.sys,
        onUnRecoverableConfigFileDiagnostic: diagnostic => {
          throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))
        }
      }
    )
    const messages = ts
      .getPreEmitDiagnostics(ts.createProgram(invalid?.fileNames ?? [], invalid?.options ?? {}))
      .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))
    expect(messages).toContain("Cannot find name 'fetch'.")
  })

  it('does not overwrite a developer-owned declaration', async () => {
    const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'ghl-action-types-'))
    directories.push(directory)
    const declarationFile = path.join(directory, 'ghl-action-calculate_score.d.ts')
    await fs.writeFile(declarationFile, 'export interface DeveloperOwned {}\n')

    await expect(
      writeWorkflowActionTypesWorkspace(directory, {
        schemaVersion: 1,
        appId: 'app-1',
        actions: [action()]
      })
    ).rejects.toThrow(/developer-owned.*will not be overwritten/i)
    await expect(fs.readFile(declarationFile, 'utf8')).resolves.toBe('export interface DeveloperOwned {}\n')
  })
})
