import { promises as fs } from 'node:fs'
import path from 'node:path'

import { MAX_PLAN_FEATURES, MAX_PLANS } from '../billing/pricing.js'
import { writeTextFileAtomic } from '../shared/atomic-file.js'
import { SUPPORTED_SERVICES } from './profile-sections.js'
import {
  WORKFLOW_ACTION_FIELD_TYPES,
  WORKFLOW_ACTION_INTERNAL_REFERENCES
} from '../workflows/actions/contract.js'
import {
  WORKFLOW_ACTION_KEY_MAX_LENGTH,
  WORKFLOW_ACTION_KEY_PATTERN
} from '../workflows/actions/key.js'
import {
  WORKFLOW_TRIGGER_FIELD_TYPES,
  WORKFLOW_TRIGGER_INTERNAL_REFERENCES
} from '../workflows/triggers/contract.js'
import {
  WORKFLOW_FIELD_KEY_MAX_LENGTH,
  WORKFLOW_REFERENCE_MAX_LENGTH,
  WORKFLOW_VERSION_MAX_LENGTH
} from '../workflows/shared/value-validation.js'

export type JsonSchema = Record<string, unknown>

export const JSON_SCHEMA_NAMES = [
  'app',
  'webhooks',
  'workflow-action',
  'workflow-trigger',
  'subscription',
  'usage-based'
] as const

export type JsonSchemaName = typeof JSON_SCHEMA_NAMES[number]

export const JSON_SCHEMA_RELATIVE_PATHS: Readonly<Record<JsonSchemaName, string>> = {
  app: '.ghl/schemas/ghl-app.schema.json',
  webhooks: '.ghl/schemas/ghl-webhooks.schema.json',
  'workflow-action': '.ghl/schemas/ghl-workflow-action.schema.json',
  'workflow-trigger': '.ghl/schemas/ghl-workflow-trigger.schema.json',
  subscription: '.ghl/schemas/ghl-subscription.schema.json',
  'usage-based': '.ghl/schemas/ghl-usage-based.schema.json'
}

export const JSON_SCHEMA_REFERENCES: Readonly<Record<JsonSchemaName, string>> = {
  app: './.ghl/schemas/ghl-app.schema.json',
  webhooks: '../../.ghl/schemas/ghl-webhooks.schema.json',
  'workflow-action': '../../../../.ghl/schemas/ghl-workflow-action.schema.json',
  'workflow-trigger': '../../../../.ghl/schemas/ghl-workflow-trigger.schema.json',
  subscription: '../../.ghl/schemas/ghl-subscription.schema.json',
  'usage-based': '../../.ghl/schemas/ghl-usage-based.schema.json'
}

const JSON_SCHEMA_DRAFT = 'http://json-schema.org/draft-07/schema#'
const RESOURCE_IDENTIFIER_PATTERN = '^[A-Za-z0-9_-]{1,128}$'
const WORKFLOW_VERSION_PATTERN = '^\\d{1,10}\\.\\d{1,10}$'
const HEADER_NAME_PATTERN = "^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$"

const stringValue = (): JsonSchema => ({ type: 'string' })
const nonEmptyString = (): JsonSchema => ({ type: 'string', minLength: 1 })
const nonBlankString = (): JsonSchema => ({ type: 'string', minLength: 1, pattern: '\\S' })
const booleanValue = (): JsonSchema => ({ type: 'boolean' })
const integer = (minimum?: number, maximum?: number): JsonSchema => ({
  type: 'integer',
  ...(minimum === undefined ? {} : { minimum }),
  ...(maximum === undefined ? {} : { maximum })
})
const stringArray = (options: { maxItems?: number; minItems?: number; uniqueItems?: boolean } = {}): JsonSchema => ({
  type: 'array',
  items: stringValue(),
  ...options
})
const arrayOf = (
  items: JsonSchema,
  options: { maxItems?: number; minItems?: number; uniqueItems?: boolean } = {}
): JsonSchema => ({
  type: 'array',
  items,
  ...options
})
const reference = (name: string): JsonSchema => ({ $ref: `#/definitions/${name}` })
const object = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
  additionalProperties: boolean | JsonSchema = false
): JsonSchema => ({
  type: 'object',
  properties,
  ...(required.length === 0 ? {} : { required }),
  additionalProperties
})
const arbitraryObject = (): JsonSchema => ({ type: 'object' })
const nullableNumber = (constraints: JsonSchema = {}): JsonSchema => ({ type: ['number', 'null'], ...constraints })

const schemaProperty = (): JsonSchema => ({
  type: 'string',
  format: 'uri-reference',
  description: 'Local JSON Schema used by editors. The CLI treats this property as file metadata.'
})

function rootSchema(
  name: JsonSchemaName,
  title: string,
  properties: Record<string, JsonSchema>,
  required: string[],
  definitions: Record<string, JsonSchema> = {}
): JsonSchema {
  return {
    $schema: JSON_SCHEMA_DRAFT,
    $id: path.posix.basename(JSON_SCHEMA_RELATIVE_PATHS[name]),
    $comment: 'Generated by the GHL CLI. Run `ghl app pull` to regenerate. Do not edit manually.',
    title,
    type: 'object',
    properties: { $schema: schemaProperty(), ...properties },
    required,
    additionalProperties: false,
    ...(Object.keys(definitions).length === 0 ? {} : { definitions })
  }
}

const appBaseSchema = rootSchema(
  'app',
  'HighLevel App Manifest',
  {
    schemaVersion: { const: 1 },
    appId: { type: 'string', pattern: RESOURCE_IDENTIFIER_PATTERN },
    versionId: { type: 'string', pattern: RESOURCE_IDENTIFIER_PATTERN },
    createdAt: stringValue(),
    version: stringValue(),
    status: stringValue(),
    appType: stringValue(),
    basicInfo: object(
      {
        name: stringValue(),
        tagline: stringValue(),
        companyName: stringValue(),
        contact: object({ name: stringValue(), email: stringValue() }, ['name', 'email']),
        website: stringValue(),
        category: stringValue(),
        subcategory: stringArray({ maxItems: 3, uniqueItems: true }),
        businessNiche: stringArray({ maxItems: 3, uniqueItems: true }),
        logoUrl: stringValue()
      },
      ['name', 'tagline', 'companyName', 'contact', 'website', 'category', 'subcategory', 'businessNiche', 'logoUrl']
    ),
    listing: object(
      {
        private: booleanValue(),
        userTypes: arrayOf(
          { enum: ['Company', 'Location'] },
          { minItems: 1, maxItems: 2, uniqueItems: true }
        ),
        isWhiteLabelFriendly: booleanValue(),
        isAgencyBulkInstallEnabled: booleanValue(),
        searchKeywords: stringArray({ uniqueItems: true })
      },
      ['private', 'userTypes', 'isWhiteLabelFriendly', 'isAgencyBulkInstallEnabled', 'searchKeywords']
    ),
    profiles: object(
      {
        agency: object(
          {
            description: stringValue(),
            previewImageUrls: stringArray({ maxItems: 9 }),
            previewVideoUrl: stringValue()
          },
          ['description', 'previewImageUrls', 'previewVideoUrl']
        ),
        subAccount: object(
          {
            enabled: booleanValue(),
            description: stringValue(),
            previewImageUrls: stringArray({ maxItems: 9 }),
            previewVideoUrl: stringValue()
          },
          ['enabled', 'description', 'previewImageUrls', 'previewVideoUrl']
        )
      },
      ['agency', 'subAccount']
    ),
    oauth: object(
      {
        allowedScopes: stringArray({ uniqueItems: true }),
        redirectUris: stringArray({ uniqueItems: true }),
        defaults: object(
          {
            clientKey: { type: ['string', 'null'] },
            redirectUrl: { type: ['string', 'null'] }
          },
          ['clientKey', 'redirectUrl']
        ),
        clientKeys: arrayOf(
          object(
            { id: stringValue(), name: stringValue(), isDefault: booleanValue() },
            ['id', 'name', 'isDefault']
          )
        )
      },
      ['allowedScopes', 'redirectUris', 'defaults', 'clientKeys']
    ),
    supportConfig: object(
      {
        supportEmail: stringValue(),
        supportPhone: stringValue(),
        websiteUrl: stringValue(),
        documentationUrl: stringValue(),
        termsAndConditionsUrl: stringValue(),
        privacyPolicyUrl: stringValue(),
        supportedServices: arrayOf(
          { enum: [...SUPPORTED_SERVICES] },
          { uniqueItems: true }
        )
      },
      [
        'supportEmail',
        'supportPhone',
        'websiteUrl',
        'documentationUrl',
        'termsAndConditionsUrl',
        'privacyPolicyUrl',
        'supportedServices'
      ]
    ),
    billing: object(
      {
        billingType: { enum: ['free', 'freemium', 'paid'] },
        isPaidApp: booleanValue(),
        isFreemium: booleanValue(),
        externalBilling: booleanValue(),
        externalBillingUrl: stringValue(),
        hasFreeTrial: booleanValue(),
        freeTrialDuration: nullableNumber(),
        hasUsageBasedPrice: booleanValue(),
        paymentType: stringValue(),
        oneTimePrice: nullableNumber(),
        additionalInfoForBilling: stringValue()
      },
      [
        'billingType',
        'isPaidApp',
        'isFreemium',
        'externalBilling',
        'externalBillingUrl',
        'hasFreeTrial',
        'freeTrialDuration',
        'hasUsageBasedPrice',
        'paymentType',
        'oneTimePrice',
        'additionalInfoForBilling'
      ]
    ),
    review: object(
      {
        endToEndDemoUrl: stringValue(),
        scopesDemoUrl: stringValue(),
        additionalDetails: stringValue(),
        privateReason: stringValue()
      },
      ['endToEndDemoUrl', 'scopesDemoUrl', 'additionalDetails', 'privateReason']
    )
  },
  [
    'schemaVersion',
    'appId',
    'versionId',
    'version',
    'status',
    'appType',
    'basicInfo',
    'listing',
    'profiles',
    'oauth',
    'supportConfig',
    'billing',
    'review'
  ]
)

const appSchema: JsonSchema = {
  ...appBaseSchema,
  allOf: [
    {
      if: {
        properties: { appType: { not: { const: 'template' } } },
        required: ['appType']
      },
      then: {
        properties: {
          basicInfo: {
            properties: { name: nonBlankString() }
          }
        }
      }
    }
  ]
}

const webhookSchema = rootSchema(
  'webhooks',
  'HighLevel Webhook Manifest',
  {
    schemaVersion: { const: 1 },
    appId: { type: 'string', pattern: RESOURCE_IDENTIFIER_PATTERN },
    versionId: { type: 'string', pattern: RESOURCE_IDENTIFIER_PATTERN },
    webhookUrl: stringValue(),
    subscribedEvents: arrayOf(
      object({ name: nonEmptyString(), url: stringValue() }, ['name'])
    )
  },
  ['schemaVersion', 'appId', 'versionId', 'webhookUrl', 'subscribedEvents']
)

const headersSchema = (): JsonSchema => ({
  type: 'object',
  propertyNames: { pattern: HEADER_NAME_PATTERN },
  additionalProperties: nonEmptyString()
})

const workflowInfoSchema = (limits = false): JsonSchema => object(
  {
    name: nonEmptyString(),
    description: { type: 'string', ...(limits ? { maxLength: 200 } : {}) },
    summary: { type: 'string', ...(limits ? { maxLength: 500 } : {}) },
    groupName: stringValue(),
    keywords: stringArray(),
    icon: stringValue(),
    screenshots: stringArray()
  },
  ['name']
)

const workflowOptionSchema = (): JsonSchema => object(
  {
    label: nonEmptyString(),
    value: nonEmptyString(),
    description: stringValue(),
    disabled: booleanValue(),
    icon: stringValue(),
    iconUrl: stringValue()
  },
  ['label', 'value']
)

const actionDefinitions: Record<string, JsonSchema> = {
  actionInfo: workflowInfoSchema(),
  actionOption: workflowOptionSchema(),
  headers: headersSchema(),
  validationRule: object(
    { rule: nonEmptyString(), errorMessage: nonEmptyString() },
    ['rule', 'errorMessage']
  ),
  fetchOptions: object({
    url: stringValue(),
    queryParams: arbitraryObject(),
    headers: reference('headers'),
    route: stringValue(),
    serviceName: stringValue(),
    version: stringValue(),
    source: stringValue(),
    sourceId: stringValue(),
    body: arbitraryObject()
  }),
  dynamicFieldsConfig: object({
    url: stringValue(),
    headers: reference('headers'),
    route: stringValue(),
    serviceName: stringValue(),
    customGenerator: stringValue(),
    method: { enum: ['DELETE', 'GET', 'PATCH', 'POST', 'PUT'] },
    labelField: stringValue(),
    valueField: stringValue(),
    path: stringValue(),
    dependsOn: stringArray(),
    postProcessor: stringValue(),
    queryParams: arbitraryObject(),
    version: stringValue(),
    source: stringValue(),
    sourceId: stringValue(),
    body: arbitraryObject()
  }),
  pagination: object({
    strategy: { enum: ['limit_offset', 'page', 'last_page', 'cursor', 'next_url'] },
    pageParam: stringValue(),
    perPageParam: stringValue(),
    limitParam: stringValue(),
    offsetParam: stringValue(),
    cursorParam: stringValue(),
    nextCursorField: stringValue(),
    syncTokenField: stringValue(),
    syncTokenParam: stringValue(),
    searchParam: stringValue(),
    enabled: booleanValue(),
    perPageValue: integer(0),
    startingPage: integer(0),
    limitValue: integer(0),
    supportsSearch: booleanValue(),
    fetchAllPages: booleanValue(),
    order: { enum: ['asc', 'desc'] },
    searchDetail: reference('dynamicSourceDetail'),
    singleDetail: reference('dynamicSourceDetail')
  }),
  dynamicSourceDetail: object({
    executionType: { enum: ['API', 'CODE'] },
    code: stringValue(),
    url: stringValue(),
    method: { enum: ['DELETE', 'GET', 'PATCH', 'POST', 'PUT'] },
    headers: reference('headers'),
    labelField: stringValue(),
    valueField: stringValue(),
    path: stringValue(),
    body: arbitraryObject(),
    postProcessor: stringValue()
  }),
  dynamicSource: object({
    executionType: { enum: ['API', 'CODE'] },
    code: stringValue(),
    url: stringValue(),
    method: { enum: ['DELETE', 'GET', 'PATCH', 'POST', 'PUT'] },
    headers: reference('headers'),
    labelField: stringValue(),
    valueField: stringValue(),
    path: stringValue(),
    body: arbitraryObject(),
    postProcessor: stringValue(),
    pagination: reference('pagination')
  }),
  inputConfig: object({
    maxItems: integer(0),
    lockDefaultKeys: booleanValue(),
    addItemLabel: stringValue(),
    innerFields: stringArray(),
    itemLabel: stringValue(),
    minSets: integer(0),
    maxSets: integer(0),
    richTextEditorType: { enum: ['html', 'plain-text'] }
  }),
  fieldOptions: object({
    allowedFileTypes: stringArray(),
    showTextFiles: booleanValue(),
    showUrlFiles: booleanValue(),
    isClearable: booleanValue()
  }),
  variantConfig: object({
    columns: integer(2, 5),
    allowDeselect: booleanValue(),
    tileSize: { enum: ['sm', 'md', 'lg'] },
    showDescription: booleanValue()
  }),
  actionInput: object(
    {
      field: {
        type: 'string',
        minLength: 1,
        maxLength: WORKFLOW_FIELD_KEY_MAX_LENGTH,
        pattern: '^(?:DYNAMIC|[A-Za-z][A-Za-z0-9_]*)$'
      },
      title: nonEmptyString(),
      required: booleanValue(),
      fieldType: { enum: [...WORKFLOW_ACTION_FIELD_TYPES] },
      helpText: stringValue(),
      placeholder: stringValue(),
      validations: arrayOf(reference('validationRule')),
      value: stringValue(),
      options: arrayOf(reference('actionOption'), { minItems: 1 }),
      mappedTo: { enum: ['', ...WORKFLOW_ACTION_INTERNAL_REFERENCES] },
      fetchOptions: reference('fetchOptions'),
      hasDynamicOptions: booleanValue(),
      dynamicSource: reference('dynamicSource'),
      dynamicFieldsConfig: reference('dynamicFieldsConfig'),
      altersDynamicField: booleanValue(),
      allowCustomInputPicker: booleanValue(),
      customInputHelperText: stringValue(),
      eventListeners: stringArray(),
      resetValue: booleanValue(),
      sortOptions: booleanValue(),
      order: integer(0),
      disabled: booleanValue(),
      dependentFilters: stringArray(),
      showOperator: booleanValue(),
      useArrayToArrayComparison: booleanValue(),
      config: reference('inputConfig'),
      showHelpTextAsInfoToolTip: booleanValue(),
      disableDatesFunction: stringValue(),
      postProcessor: stringValue(),
      showBelowCustomField: booleanValue(),
      fieldOptions: reference('fieldOptions'),
      timezoneSourceField: stringValue(),
      hideAIToggle: booleanValue(),
      variant: { enum: ['standard', 'tile-picker'] },
      variantConfig: reference('variantConfig'),
      group: stringValue(),
      groupDivider: booleanValue(),
      translationKey: stringValue()
    },
    ['field', 'title', 'fieldType']
  ),
  actionCustomVariable: object(
    {
      name: nonEmptyString(),
      reference: {
        type: 'string',
        minLength: 1,
        maxLength: WORKFLOW_REFERENCE_MAX_LENGTH,
        pattern: '^\\S+$'
      },
      fieldType: { enum: ['array', 'boolean', 'date', 'numerical', 'string'] },
      options: arrayOf(reference('actionOption'), { minItems: 1 }),
      fetchOptions: reference('fetchOptions')
    },
    ['name', 'reference', 'fieldType']
  ),
  executionConfig: {
    ...object(
      {
        type: { enum: ['API', 'CODE'] },
        url: stringValue(),
        method: { enum: ['DELETE', 'GET', 'PATCH', 'POST', 'PUT'] },
        headers: reference('headers'),
        codeFile: nonEmptyString(),
        pauseExecution: booleanValue()
      },
      ['type']
    ),
    allOf: [
      {
        if: { properties: { type: { const: 'API' } } },
        then: { not: { required: ['codeFile'] } }
      },
      {
        if: { properties: { type: { const: 'CODE' } } },
        then: {
          required: ['codeFile'],
          not: { anyOf: [{ required: ['url'] }, { required: ['method'] }, { required: ['headers'] }] }
        }
      }
    ]
  },
  branchField: object(
    {
      field: { type: 'string', minLength: 1, maxLength: WORKFLOW_REFERENCE_MAX_LENGTH },
      title: nonEmptyString(),
      required: booleanValue(),
      fieldType: { enum: ['dynamic', 'multiselect', 'numerical', 'phone', 'select', 'string', 'textarea', 'toggle'] },
      options: arrayOf(reference('actionOption'), { minItems: 1 }),
      mappedTo: stringValue(),
      altersDynamicField: booleanValue(),
      disabled: booleanValue(),
      placeholder: stringValue(),
      helpText: stringValue(),
      value: stringValue(),
      sortOptions: booleanValue()
    },
    ['field', 'title', 'fieldType']
  ),
  branchInfo: object({
    branchNameLabel: stringValue(),
    branchNameHelpText: stringValue(),
    branchNamePlaceholder: stringValue(),
    sectionTitle: stringValue(),
    sectionDescription: stringValue(),
    deleteAlertTitle: stringValue(),
    deleteAlertDescription: stringValue(),
    addButtonLabel: stringValue(),
    allowNewCondition: booleanValue(),
    isDefaultBranchEditable: booleanValue(),
    showBranchSection: booleanValue()
  }),
  branchFetchOptions: object(
    {
      serviceName: nonEmptyString(),
      route: nonEmptyString(),
      version: stringValue(),
      source: stringValue(),
      sourceId: stringValue(),
      body: arbitraryObject(),
      headers: reference('headers')
    },
    ['serviceName', 'route']
  ),
  branch: object(
    {
      id: nonEmptyString(),
      branchName: nonEmptyString(),
      conditionType: { enum: ['default', 'user-defined'] },
      fields: arbitraryObject(),
      meta: arbitraryObject()
    },
    ['id', 'branchName', 'conditionType']
  ),
  branchesConfig: object({
    allowMultipath: booleanValue(),
    altersDynamicField: booleanValue(),
    info: reference('branchInfo'),
    fields: arrayOf(reference('branchField')),
    predefinedBranches: object({
      fetchBranches: reference('branchFetchOptions'),
      customGenerator: stringValue(),
      branches: arrayOf(reference('branch'))
    }),
    branchFieldsGenerator: stringValue()
  }),
  groupConfig: object({ dividerPosition: { enum: ['none', 'above', 'below'] } }),
  actionVersion: object(
    {
      version: {
        type: 'string',
        maxLength: WORKFLOW_VERSION_MAX_LENGTH,
        pattern: WORKFLOW_VERSION_PATTERN
      },
      status: { enum: ['draft', 'in_review', 'published'] },
      info: reference('actionInfo'),
      inputs: arrayOf(reference('actionInput')),
      customVars: arrayOf(reference('actionCustomVariable')),
      customVarsJson: arbitraryObject(),
      executionConfig: reference('executionConfig'),
      payloadCustomizationType: { enum: ['custom', 'default'] },
      customizedPayload: arbitraryObject(),
      branchesConfig: reference('branchesConfig'),
      sectionOrder: stringArray({ uniqueItems: true }),
      groupConfigs: { type: 'object', additionalProperties: reference('groupConfig') }
    },
    ['version', 'status', 'info']
  )
}

const workflowActionSchema = rootSchema(
  'workflow-action',
  'HighLevel Workflow Action',
  {
    schemaVersion: { const: 1 },
    key: {
      type: 'string',
      minLength: 1,
      maxLength: WORKFLOW_ACTION_KEY_MAX_LENGTH,
      pattern: WORKFLOW_ACTION_KEY_PATTERN.source
    },
    templateId: nonEmptyString(),
    versions: arrayOf(reference('actionVersion'), { minItems: 1 })
  },
  ['schemaVersion', 'key', 'versions'],
  actionDefinitions
)

const triggerDefinitions: Record<string, JsonSchema> = {
  triggerInfo: workflowInfoSchema(true),
  triggerOption: workflowOptionSchema(),
  headers: headersSchema(),
  externalSource: object(
    { url: nonEmptyString(), headers: reference('headers') },
    ['url']
  ),
  triggerFilter: object(
    {
      field: { type: 'string', minLength: 1, maxLength: WORKFLOW_REFERENCE_MAX_LENGTH },
      title: nonEmptyString(),
      required: booleanValue(),
      fieldType: { enum: [...WORKFLOW_TRIGGER_FIELD_TYPES] },
      options: arrayOf(reference('triggerOption'), { minItems: 1 }),
      fetchOptions: reference('externalSource'),
      mappedTo: { enum: [...WORKFLOW_TRIGGER_INTERNAL_REFERENCES] },
      altersDynamicField: booleanValue(),
      dynamicFieldsConfig: reference('externalSource')
    },
    ['field', 'title', 'fieldType']
  ),
  triggerCustomVariable: object(
    {
      name: nonEmptyString(),
      reference: {
        type: 'string',
        minLength: 1,
        maxLength: WORKFLOW_REFERENCE_MAX_LENGTH,
        pattern: '^\\S+$'
      },
      fieldType: { enum: ['array', 'boolean', 'date', 'numerical', 'string'] }
    },
    ['name', 'reference', 'fieldType']
  ),
  subscriptionConfig: object({ url: stringValue(), headers: reference('headers') }),
  triggerVersion: object(
    {
      version: {
        type: 'string',
        maxLength: WORKFLOW_VERSION_MAX_LENGTH,
        pattern: WORKFLOW_VERSION_PATTERN
      },
      status: { enum: ['draft', 'in_review', 'published'] },
      info: reference('triggerInfo'),
      filters: arrayOf(reference('triggerFilter')),
      customVars: arrayOf(reference('triggerCustomVariable')),
      customVarsJson: arbitraryObject(),
      subscriptionConfig: reference('subscriptionConfig')
    },
    ['version', 'status', 'info']
  )
}

const workflowTriggerSchema = rootSchema(
  'workflow-trigger',
  'HighLevel Workflow Trigger',
  {
    schemaVersion: { const: 1 },
    key: {
      type: 'string',
      minLength: 1,
      maxLength: WORKFLOW_ACTION_KEY_MAX_LENGTH,
      pattern: WORKFLOW_ACTION_KEY_PATTERN.source
    },
    templateId: nonEmptyString(),
    versions: arrayOf(reference('triggerVersion'), { minItems: 1 })
  },
  ['schemaVersion', 'key', 'versions'],
  triggerDefinitions
)

const subscriptionSchema = rootSchema(
  'subscription',
  'HighLevel Subscription Plans',
  {
    schemaVersion: { const: 1 },
    appId: nonEmptyString(),
    plans: arrayOf(reference('subscriptionPlan'), { maxItems: MAX_PLANS })
  },
  ['schemaVersion', 'appId', 'plans'],
  {
    subscriptionPlan: object(
      {
        id: nonEmptyString(),
        name: nonEmptyString(),
        features: arrayOf(nonEmptyString(), { maxItems: MAX_PLAN_FEATURES }),
        paymentTime: { enum: ['month', 'year', 'life_time'] },
        paymentType: { enum: ['recurring', 'one_time'] },
        amount: { type: 'number', minimum: 0 },
        locationAmount: { type: 'number', minimum: 0 },
        freePlan: booleanValue(),
        freeForAgency: booleanValue(),
        freeForLocation: booleanValue()
      },
      [
        'name',
        'features',
        'paymentTime',
        'paymentType',
        'amount',
        'freePlan',
        'freeForAgency',
        'freeForLocation'
      ]
    )
  }
)

const usageBasedSchema = rootSchema(
  'usage-based',
  'HighLevel Usage-Based Billing',
  {
    schemaVersion: { const: 1 },
    appId: nonEmptyString(),
    meters: arrayOf(reference('usageMeter'))
  },
  ['schemaVersion', 'appId', 'meters'],
  {
    usageTier: object(
      {
        id: nonEmptyString(),
        name: nonEmptyString(),
        minVolume: { type: 'number', minimum: 0 },
        maxVolume: nullableNumber({ exclusiveMinimum: 0 }),
        pricePerUnit: { type: 'number', minimum: 0.000001, maximum: 200 },
        minPricePerUnit: { type: 'number', minimum: 0.000001, maximum: 200 },
        maxPricePerUnit: { type: 'number', minimum: 0.000001, maximum: 200 },
        executionLimitPerCycle: integer(1)
      },
      ['name', 'minVolume', 'maxVolume', 'pricePerUnit', 'executionLimitPerCycle']
    ),
    usageMeter: object(
      {
        id: nonEmptyString(),
        productType: { enum: ['conversation_provider', 'workflow_action', 'workflow_trigger', 'custom'] },
        productId: { type: 'string', minLength: 1, maxLength: 250 },
        productName: nonEmptyString(),
        customPriceType: { enum: ['fixed', 'dynamic'] },
        usageUnit: { type: 'string', minLength: 1, maxLength: 19 },
        direction: { enum: ['inbound', 'outbound'] },
        pricingPageUrl: stringValue(),
        tiers: arrayOf(reference('usageTier'), { minItems: 1 })
      },
      ['productType', 'productId', 'productName', 'customPriceType', 'usageUnit', 'tiers']
    )
  }
)

const JSON_SCHEMAS: Readonly<Record<JsonSchemaName, JsonSchema>> = {
  app: appSchema,
  webhooks: webhookSchema,
  'workflow-action': workflowActionSchema,
  'workflow-trigger': workflowTriggerSchema,
  subscription: subscriptionSchema,
  'usage-based': usageBasedSchema
}

const JSON_SCHEMA_FILE_MATCHES: Readonly<Record<JsonSchemaName, string[]>> = {
  app: ['ghl-app.json'],
  webhooks: ['src/webhooks/ghl-webhooks.json'],
  'workflow-action': ['src/modules/workflows/actions/*.json'],
  'workflow-trigger': ['src/modules/workflows/triggers/*.json'],
  subscription: ['src/billing/subscription.json'],
  'usage-based': ['src/billing/usage-based.json']
}

export interface JsonSchemaWorkspaceResult {
  schemaDirectory: string
  schemaFiles: string[]
  vscodeSettingsFile: string
  vscodeSettingsCreated: boolean
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function withJsonSchemaReference<T extends object>(value: T, name: JsonSchemaName): T & { $schema: string } {
  const source = value as T & { $schema?: unknown }
  const { $schema: _schema, ...manifest } = source
  return { $schema: JSON_SCHEMA_REFERENCES[name], ...manifest } as T & { $schema: string }
}

export function withoutJsonSchemaReference<T>(value: T): T {
  if (!isRecord(value) || !Object.hasOwn(value, '$schema')) return value
  const { $schema: _schema, ...manifest } = value
  return manifest as T
}

export function getJsonSchema(name: JsonSchemaName): JsonSchema {
  return structuredClone(JSON_SCHEMAS[name])
}

async function lstatIfPresent(target: string): Promise<Awaited<ReturnType<typeof fs.lstat>> | undefined> {
  try {
    return await fs.lstat(target)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

async function assertSchemaPathsSafe(directory: string): Promise<void> {
  const workspaceStat = await lstatIfPresent(directory)
  if (!workspaceStat) throw new Error(`App workspace "${directory}" does not exist.`)
  if (workspaceStat.isSymbolicLink()) throw new Error(`App workspace "${directory}" cannot be a symbolic link.`)
  if (!workspaceStat.isDirectory()) throw new Error(`App workspace "${directory}" is not a directory.`)

  for (const [relativePath, label] of [
    ['.ghl', 'Workspace state directory'],
    [path.join('.ghl', 'schemas'), 'JSON schema directory']
  ] as const) {
    const target = path.join(directory, relativePath)
    const stat = await lstatIfPresent(target)
    if (!stat) continue
    if (stat.isSymbolicLink()) throw new Error(`${label} "${target}" cannot be a symbolic link.`)
    if (!stat.isDirectory()) throw new Error(`${label} "${target}" is not a directory.`)
  }

  for (const name of JSON_SCHEMA_NAMES) {
    const file = path.join(directory, JSON_SCHEMA_RELATIVE_PATHS[name])
    const stat = await lstatIfPresent(file)
    if (!stat) continue
    if (stat.isSymbolicLink()) throw new Error(`JSON schema file "${file}" cannot be a symbolic link.`)
    if (!stat.isFile()) throw new Error(`JSON schema path "${file}" is not a regular file.`)
  }
}

async function writeSchemaIfChanged(file: string, schema: JsonSchema): Promise<void> {
  const contents = `${JSON.stringify(schema, null, 2)}\n`
  try {
    if (await fs.readFile(file, 'utf8') === contents) return
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  await writeTextFileAtomic(file, contents, 0o644)
}

async function createVscodeSettings(directory: string): Promise<{ created: boolean; file: string }> {
  const vscodeDirectory = path.join(directory, '.vscode')
  const settingsFile = path.join(vscodeDirectory, 'settings.json')
  const vscodeStat = await lstatIfPresent(vscodeDirectory)
  if (vscodeStat && (!vscodeStat.isDirectory() || vscodeStat.isSymbolicLink())) {
    return { created: false, file: settingsFile }
  }
  if (await lstatIfPresent(settingsFile)) return { created: false, file: settingsFile }

  await fs.mkdir(vscodeDirectory, { recursive: true, mode: 0o755 })
  const settings = {
    'json.schemas': JSON_SCHEMA_NAMES.map(name => ({
      fileMatch: JSON_SCHEMA_FILE_MATCHES[name],
      url: `./${JSON_SCHEMA_RELATIVE_PATHS[name]}`
    }))
  }
  try {
    await fs.writeFile(settingsFile, `${JSON.stringify(settings, null, 2)}\n`, {
      encoding: 'utf8',
      flag: 'wx',
      mode: 0o644
    })
    return { created: true, file: settingsFile }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') return { created: false, file: settingsFile }
    throw error
  }
}

export async function writeJsonSchemaWorkspace(inputDirectory: string): Promise<JsonSchemaWorkspaceResult> {
  const directory = path.resolve(inputDirectory)
  await assertSchemaPathsSafe(directory)
  const schemaDirectory = path.join(directory, '.ghl', 'schemas')
  await fs.mkdir(schemaDirectory, { recursive: true, mode: 0o700 })
  const schemaFiles = JSON_SCHEMA_NAMES.map(name => path.join(directory, JSON_SCHEMA_RELATIVE_PATHS[name]))
  await Promise.all(JSON_SCHEMA_NAMES.map((name, index) => writeSchemaIfChanged(schemaFiles[index], JSON_SCHEMAS[name])))
  const vscode = await createVscodeSettings(directory)
  return {
    schemaDirectory,
    schemaFiles,
    vscodeSettingsFile: vscode.file,
    vscodeSettingsCreated: vscode.created
  }
}
